apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "razas-api.fullname" . }}
  labels:
    app: {{ include "razas-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "razas-api.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "razas-api.fullname" . }}
    spec:
      containers:
        - name: razas-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
